# Generated by Django 4.1.2 on 2022-10-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_lyric_content_alter_song_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
