# Generated by Django 4.1.2 on 2022-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_alter_artiste_first_name_alter_artiste_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='first_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='stage_name',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=264),
        ),
    ]
